In [2]:
print("hello world")

hello world


In [5]:
if 5 > 2:
    print(" 5 is greater than 2")

 5 is greater than 2


In [6]:
a = 1
a

1

In [7]:
c
print(c)

NameError: name 'c' is not defined

In [8]:
a, b, c = 1, 2, 3

print(a)
print(b)
print(c)

1
2
3


In [9]:
a = "1"
b = 5
print(a+b)

TypeError: can only concatenate str (not "int") to str

In [10]:
a = int(a)
print(a + b)

6


In [12]:
a = "str+"
b = 5

b = str(b)

print(a+b)

str+5


In [13]:
list1 = [1, 2, 3, 4]
print(list1[1])

2


In [14]:
list = ["d", 1, 2, 3]
list.append("5")
print(list)

['d', 1, 2, 3, '5']


In [15]:
list.pop()

'5'

In [16]:
list.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [18]:
list = [2, 1, 4, 5]
list.sort()
list

[1, 2, 4, 5]

In [22]:
import pandas as pd
model_infor = {
    'model_name': 'gbm',
    'data_frame': pd.DataFrame({
        "col": ['1', '2', '3'],
        "y": [1, 2, 3]
    })
}
model_infor

{'model_name': 'gbm',
 'data_frame':   col  y
 0   1  1
 1   2  2
 2   3  3}

In [23]:
model_infor.items()

dict_items([('model_name', 'gbm'), ('data_frame',   col  y
0   1  1
1   2  2
2   3  3)])

In [24]:
i = 1
while i < 6:
    print(i)
    i = i+1


1
2
3
4
5


In [25]:
def sum(a, b):
    return a+b


sum(1, 2)

3

In [26]:
# ndim() in R size in matlab
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])